name: build
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ankane/psycopg
          ref: copy-performance
      - run: sudo service postgresql start
      - run: sudo -u postgres createuser runner -s
      - run: createdb runner
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install "psycopg[binary]"
      - run: tests/scripts/copytest.py --colsize 200 --nrecs 1000000
      - run: pip install -e psycopg
      - run: tests/scripts/copytest.py --colsize 200 --nrecs 1000000
  mac:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ankane/psycopg
          ref: copy-performance
      - run: brew install postgresql
      - run: brew services start postgresql
      - run: createdb runner
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install "psycopg[binary]"
      - run: tests/scripts/copytest.py --nrecs 1000000
      - run: pip install -e psycopg
      - run: tests/scripts/copytest.py --nrecs 1000000
