name: build
on: push
jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ankane/psycopg
          ref: copy-performance
          fetch-depth: 0
      - run: sc config postgresql-x64-14 start=auto
      - run: net start postgresql-x64-14
      - run: echo $PGBIN
      - run: $PGBIN/createdb runner
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install -e psycopg
      - run: tests/scripts/copytest.py --nrecs 1000000
      - run: git revert --no-commit 921b4afe8171e6732405b575b92fe1f8a58c347a
      - run: tests/scripts/copytest.py --nrecs 1000000
